In [1]:
import pandas as pd
from pathlib import Path

# 5a5b energy difference: b3lyp pbe0 tzvp svp

In [6]:
csv_path = Path('./energies_functional_basis.csv')
df = pd.read_csv(csv_path)
print(df.columns)
df

Index(['structure', 'method', '5a au', '5b au'], dtype='object')

     structure         method        5a au        5b au
0     original        article -5000.191792 -5000.191502
1     original  b3lyp/dgdzvp2 -5000.191951 -5000.191543
2     original      b3lyp/svp -4999.513907 -5000.257983
3     original       pbe0/svp -4997.605881 -4997.615804
4     original      pbe0/tzvp -4999.054146 -4999.057686
5     original   pbe0/dgdzvp2 -4998.276882 -4998.278460
6  pbe0dgdzvp2   pbe0/dgdzvp2 -4998.278606 -4998.280510
7      pbe0svp       pbe0/svp -4997.617272 -4997.628051
8      pbe0svp      pbe0/tzvp -4999.058998 -4999.063063
9     pbe0tzvp      pbe0/tzvp -4999.060280 -4999.064222

In [7]:
df.loc[:, "dE au"] = df.loc[:, '5b au'] - df.loc[:, '5a au']
hartree_to_eV = 27.2114
df.loc[:, 'dE eV'] = df.loc[:, "dE au"] * hartree_to_eV
df

     structure         method        5a au        5b au     dE au      dE eV
0     original        article -5000.191792 -5000.191502  0.000290   0.007891
1     original  b3lyp/dgdzvp2 -5000.191951 -5000.191543  0.000408   0.011105
2     original      b3lyp/svp -4999.513907 -5000.257983 -0.744076 -20.247358
3     original       pbe0/svp -4997.605881 -4997.615804 -0.009924  -0.270039
4     original      pbe0/tzvp -4999.054146 -4999.057686 -0.003540  -0.096325
5     original   pbe0/dgdzvp2 -4998.276882 -4998.278460 -0.001578  -0.042947
6  pbe0dgdzvp2   pbe0/dgdzvp2 -4998.278606 -4998.280510 -0.001904  -0.051809
7      pbe0svp       pbe0/svp -4997.617272 -4997.628051 -0.010779  -0.293325
8      pbe0svp      pbe0/tzvp -4999.058998 -4999.063063 -0.004065  -0.110618
9     pbe0tzvp      pbe0/tzvp -4999.060280 -4999.064222 -0.003942  -0.107268

dE/dE_article

In [8]:
df.loc[:, 'dE/dE_article'] = df.loc[:, 'dE eV'] / df.loc[0, 'dE eV']
df

,structure,method,5a au,5b au,dE au,dE eV,dE/dE_article
0,original,article,-5000.191792,-5000.191502,0.000290,0.007891,1.000000
1,original,b3lyp/dgdzvp2,-5000.191951,-5000.191543,0.000408,0.011105,1.407276
2,original,b3lyp/svp,-4999.513907,-5000.257983,-0.744076,-20.247358,-2565.780380
3,original,pbe0/svp,-4997.605881,-4997.615804,-0.009924,-0.270039,-34.219793
4,original,pbe0/tzvp,-4999.054146,-4999.057686,-0.003540,-0.096325,-12.206483
5,original,pbe0/dgdzvp2,-4998.276882,-4998.278460,-0.001578,-0.042947,-5.442379
6,pbe0dgdzvp2,pbe0/dgdzvp2,-4998.278606,-4998.280510,-0.001904,-0.051809,-6.565379
7,pbe0svp,pbe0/svp,-4997.617272,-4997.628051,-0.010779,-0.293325,-37.170655
8,pbe0svp,pbe0/tzvp,-4999.058998,-4999.063063,-0.004065,-0.110618,-14.017655
9,pbe0tzvp,pbe0/tzvp,-4999.060280,-4999.064222,-0.003942,-0.107268,-13.593172

In [5]:
df_original = df.iloc[0:5, :].drop(columns=["dE au"])
df_original

  structure         method        5a au        5b au     dE eV  dE/dE_article
0  original        article -5000.191792 -5000.191502  0.007891       1.000000
1  original  b3lyp/dgdzvp2 -5000.191951 -5000.191543  0.011105       1.407276
2  original       pbe0/svp -4997.605881 -4997.615804 -0.270039     -34.219793
3  original      pbe0/tzvp -4999.054146 -4999.057686 -0.096325     -12.206483
4  original   pbe0/dgdzvp2 -4998.276882 -4998.278460 -0.042947      -5.442379

↑↑↑ control structure = original, compare functionals and basis sets ↑↑↑

In [29]:
dfi = df.set_index('method')
df_tzvp = dfi.loc['pbe0/tzvp', :].drop(columns=["dE au"])
df_tzvp

          structure        5a au        5b au     dE eV  dE/dE_article
method
pbe0/tzvp  original -4999.054146 -4999.057686 -0.096325     -12.206483
pbe0/tzvp   pbe0svp -4999.058998 -4999.063063 -0.110618     -14.017655
pbe0/tzvp  pbe0tzvp -4999.060280 -4999.064222 -0.107268     -13.593172

↑↑↑ control method=pbe0/tzvp, compare structures: original(from the article), pbe0/svp optimized, pbe0/tzvp optimized ↑↑↑