In [1]:
import pandas as pd, re
from pathlib import Path

from parse_dftsp_grepscf_to_df import parse_grepscf

hartree_to_eV = 27.2114

# Compared DFT sp energies
pbe0/def2tzvp pbe/def2tzvp

In [2]:
energy_file_path = Path('./tio2_ChenDixon_gjf/all5_sp/sp_energy.txt')
df_sp_energies = parse_grepscf(energy_file_path)

In [3]:
df_sp_energies

   structure       opt method      sp method    energy_au
0         5a  article_article  pbe0_def2tzvp -4999.054146
1         5a       matpes_pbe  pbe0_def2tzvp -4999.050827
2         5a    matpes_r2scan  pbe0_def2tzvp -4999.055888
3         5a          mpa_mpa  pbe0_def2tzvp -4999.051394
4         5a    omat24_omat24  pbe0_def2tzvp -4999.051386
5         5a       omol25_low  pbe0_def2tzvp -4999.059019
6         5a     pbe0_def2svp  pbe0_def2tzvp -4999.058998
7         5a    pbe0_def2tzvp  pbe0_def2tzvp -4999.060280
8         5a     pbe0_dgdzvp2  pbe0_def2tzvp -4999.058794
9         5a      pbe_def2svp  pbe0_def2tzvp -4999.058532
10        5a     pbe_def2tzvp  pbe0_def2tzvp -4999.055563
11        5a  article_article   pbe_def2tzvp -4999.130072
12        5a       matpes_pbe   pbe_def2tzvp -4999.129773
13        5a    matpes_r2scan   pbe_def2tzvp -4999.129994
14        5a          mpa_mpa   pbe_def2tzvp -4999.130069
15        5a    omat24_omat24   pbe_def2tzvp -4999.130033
16        5a       omol25_low   pbe_def2tzvp -4999.127026
17        5a     pbe0_def2svp   pbe_def2tzvp -4999.121563
18        5a    pbe0_def2tzvp   pbe_def2tzvp -4999.126568
19        5a     pbe0_dgdzvp2   pbe_def2tzvp -4999.129686
20        5a      pbe_def2svp   pbe_def2tzvp -4999.129887
21        5a     pbe_def2tzvp   pbe_def2tzvp -4999.131012
22        5b  article_article  pbe0_def2tzvp -4999.057686
23        5b       matpes_pbe  pbe0_def2tzvp -4999.054039
24        5b    matpes_r2scan  pbe0_def2tzvp -4999.059767
25        5b          mpa_mpa  pbe0_def2tzvp -4999.054309
26        5b    omat24_omat24  pbe0_def2tzvp -4999.054621
27        5b       omol25_low  pbe0_def2tzvp -4999.063340
28        5b     pbe0_def2svp  pbe0_def2tzvp -4999.063063
29        5b    pbe0_def2tzvp  pbe0_def2tzvp -4999.064222
30        5b     pbe0_dgdzvp2  pbe0_def2tzvp -4999.062656
31        5b      pbe_def2svp  pbe0_def2tzvp -4999.062800
32        5b     pbe_def2tzvp  pbe0_def2tzvp -4999.059600
33        5b  article_article   pbe_def2tzvp -4999.132496
34        5b       matpes_pbe   pbe_def2tzvp -4999.131934
35        5b    matpes_r2scan   pbe_def2tzvp -4999.132919
36        5b          mpa_mpa   pbe_def2tzvp -4999.131994
37        5b    omat24_omat24   pbe_def2tzvp -4999.132106
38        5b       omol25_low   pbe_def2tzvp -4999.130478
39        5b     pbe0_def2svp   pbe_def2tzvp -4999.123890
40        5b    pbe0_def2tzvp   pbe_def2tzvp -4999.128925
41        5b     pbe0_dgdzvp2   pbe_def2tzvp -4999.132058
42        5b      pbe_def2svp   pbe_def2tzvp -4999.132172
43        5b     pbe_def2tzvp   pbe_def2tzvp -4999.133300

In [4]:
df_5apbe0 = df_sp_energies[df_sp_energies["structure"] == "5a"].loc[df_sp_energies["sp method"] == "pbe0_def2tzvp"]
df_5bpbe0 = df_sp_energies[df_sp_energies["structure"] == "5b"].loc[df_sp_energies["sp method"] == "pbe0_def2tzvp"]
df_5apbe = df_sp_energies[df_sp_energies["structure"] == "5a"].loc[df_sp_energies["sp method"] == "pbe_def2tzvp"]
df_5bpbe = df_sp_energies[df_sp_energies["structure"] == "5b"].loc[df_sp_energies["sp method"] == "pbe_def2tzvp"]

In [5]:
for df_i in [df_5apbe0, df_5bpbe0,df_5apbe, df_5bpbe]:
    df_i.insert(0, "opt method", df_i.pop("opt method"))
    df_i.insert(0, "sp method", df_i.pop("sp method"))
    df_i.reset_index(drop=True, inplace=True)

In [6]:
df_5apbe0

        sp method       opt method structure    energy_au
0   pbe0_def2tzvp  article_article        5a -4999.054146
1   pbe0_def2tzvp       matpes_pbe        5a -4999.050827
2   pbe0_def2tzvp    matpes_r2scan        5a -4999.055888
3   pbe0_def2tzvp          mpa_mpa        5a -4999.051394
4   pbe0_def2tzvp    omat24_omat24        5a -4999.051386
5   pbe0_def2tzvp       omol25_low        5a -4999.059019
6   pbe0_def2tzvp     pbe0_def2svp        5a -4999.058998
7   pbe0_def2tzvp    pbe0_def2tzvp        5a -4999.060280
8   pbe0_def2tzvp     pbe0_dgdzvp2        5a -4999.058794
9   pbe0_def2tzvp      pbe_def2svp        5a -4999.058532
10  pbe0_def2tzvp     pbe_def2tzvp        5a -4999.055563

In [7]:
df_5bpbe0

        sp method       opt method structure    energy_au
0   pbe0_def2tzvp  article_article        5b -4999.057686
1   pbe0_def2tzvp       matpes_pbe        5b -4999.054039
2   pbe0_def2tzvp    matpes_r2scan        5b -4999.059767
3   pbe0_def2tzvp          mpa_mpa        5b -4999.054309
4   pbe0_def2tzvp    omat24_omat24        5b -4999.054621
5   pbe0_def2tzvp       omol25_low        5b -4999.063340
6   pbe0_def2tzvp     pbe0_def2svp        5b -4999.063063
7   pbe0_def2tzvp    pbe0_def2tzvp        5b -4999.064222
8   pbe0_def2tzvp     pbe0_dgdzvp2        5b -4999.062656
9   pbe0_def2tzvp      pbe_def2svp        5b -4999.062800
10  pbe0_def2tzvp     pbe_def2tzvp        5b -4999.059600

In [8]:
df_5bpbe0_x = df_5bpbe0.iloc[:,2:]
df_pbe0 = pd.concat([df_5apbe0, df_5bpbe0_x], axis=1)
df_pbe0.columns.values[3] = '5a_energy_au'
df_pbe0.columns.values[5] = '5b_energy_au'
df_pbe0.drop('structure', inplace=True, axis=1)
df_pbe0

        sp method       opt method  5a_energy_au  5b_energy_au
0   pbe0_def2tzvp  article_article  -4999.054146  -4999.057686
1   pbe0_def2tzvp       matpes_pbe  -4999.050827  -4999.054039
2   pbe0_def2tzvp    matpes_r2scan  -4999.055888  -4999.059767
3   pbe0_def2tzvp          mpa_mpa  -4999.051394  -4999.054309
4   pbe0_def2tzvp    omat24_omat24  -4999.051386  -4999.054621
5   pbe0_def2tzvp       omol25_low  -4999.059019  -4999.063340
6   pbe0_def2tzvp     pbe0_def2svp  -4999.058998  -4999.063063
7   pbe0_def2tzvp    pbe0_def2tzvp  -4999.060280  -4999.064222
8   pbe0_def2tzvp     pbe0_dgdzvp2  -4999.058794  -4999.062656
9   pbe0_def2tzvp      pbe_def2svp  -4999.058532  -4999.062800
10  pbe0_def2tzvp     pbe_def2tzvp  -4999.055563  -4999.059600

In [9]:
df_5bpbe_x = df_5bpbe.iloc[:,2:]
df_pbe = pd.concat([df_5apbe, df_5bpbe_x], axis=1)
df_pbe.columns.values[3] = '5a_energy_au'
df_pbe.columns.values[5] = '5b_energy_au'
df_pbe.drop('structure', inplace=True, axis=1)
df_pbe

       sp method       opt method  5a_energy_au  5b_energy_au
0   pbe_def2tzvp  article_article  -4999.130072  -4999.132496
1   pbe_def2tzvp       matpes_pbe  -4999.129773  -4999.131934
2   pbe_def2tzvp    matpes_r2scan  -4999.129994  -4999.132919
3   pbe_def2tzvp          mpa_mpa  -4999.130069  -4999.131994
4   pbe_def2tzvp    omat24_omat24  -4999.130033  -4999.132106
5   pbe_def2tzvp       omol25_low  -4999.127026  -4999.130478
6   pbe_def2tzvp     pbe0_def2svp  -4999.121563  -4999.123890
7   pbe_def2tzvp    pbe0_def2tzvp  -4999.126568  -4999.128925
8   pbe_def2tzvp     pbe0_dgdzvp2  -4999.129686  -4999.132058
9   pbe_def2tzvp      pbe_def2svp  -4999.129887  -4999.132172
10  pbe_def2tzvp     pbe_def2tzvp  -4999.131012  -4999.133300

In [10]:
for df_i in [df_pbe0, df_pbe]:
    df_i.loc[:, "dE_eV"] = (df_i.loc[:, "5b_energy_au"] - df_i.loc[:, "5a_energy_au"]) * hartree_to_eV
    print(df_i)
    # e_ref = df_i[df_i["opt method"] == "pbe0_def2tzvp", "5a_energy_au"]
    # df_i.loc[:, "5a_energy_au_ref"]

        sp method       opt method  5a_energy_au  5b_energy_au     dE_eV
0   pbe0_def2tzvp  article_article  -4999.054146  -4999.057686 -0.096325
1   pbe0_def2tzvp       matpes_pbe  -4999.050827  -4999.054039 -0.087417
2   pbe0_def2tzvp    matpes_r2scan  -4999.055888  -4999.059767 -0.105559
3   pbe0_def2tzvp          mpa_mpa  -4999.051394  -4999.054309 -0.079314
4   pbe0_def2tzvp    omat24_omat24  -4999.051386  -4999.054621 -0.088020
5   pbe0_def2tzvp       omol25_low  -4999.059019  -4999.063340 -0.117567
6   pbe0_def2tzvp     pbe0_def2svp  -4999.058998  -4999.063063 -0.110618
7   pbe0_def2tzvp    pbe0_def2tzvp  -4999.060280  -4999.064222 -0.107268
8   pbe0_def2tzvp     pbe0_dgdzvp2  -4999.058794  -4999.062656 -0.105087
9   pbe0_def2tzvp      pbe_def2svp  -4999.058532  -4999.062800 -0.116129
10  pbe0_def2tzvp     pbe_def2tzvp  -4999.055563  -4999.059600 -0.109857
       sp method       opt method  5a_energy_au  5b_energy_au     dE_eV
0   pbe_def2tzvp  article_article  -4999.130072  -4999.132496 -0.065971
1   pbe_def2tzvp       matpes_pbe  -4999.129773  -4999.131934 -0.058788
2   pbe_def2tzvp    matpes_r2scan  -4999.129994  -4999.132919 -0.079578
3   pbe_def2tzvp          mpa_mpa  -4999.130069  -4999.131994 -0.052389
4   pbe_def2tzvp    omat24_omat24  -4999.130033  -4999.132106 -0.056420
5   pbe_def2tzvp       omol25_low  -4999.127026  -4999.130478 -0.093925
6   pbe_def2tzvp     pbe0_def2svp  -4999.121563  -4999.123890 -0.063321
7   pbe_def2tzvp    pbe0_def2tzvp  -4999.126568  -4999.128925 -0.064151
8   pbe_def2tzvp     pbe0_dgdzvp2  -4999.129686  -4999.132058 -0.064556
9   pbe_def2tzvp      pbe_def2svp  -4999.129887  -4999.132172 -0.062168
10  pbe_def2tzvp     pbe_def2tzvp  -4999.131012  -4999.133300 -0.062267

In [11]:
e_ref_a = df_pbe0.loc[df_pbe0["opt method"] == "pbe0_def2tzvp", "5a_energy_au"].iloc[0]
e_ref_b = df_pbe0.loc[df_pbe0["opt method"] == "pbe0_def2tzvp", "5b_energy_au"].iloc[0]
print(e_ref_a)
print(e_ref_b)

df_pbe0.loc[:,"5a_energy_eV_ref"] = (df_pbe0.loc[:,"5a_energy_au"] - e_ref_a) * hartree_to_eV
df_pbe0.loc[:,"5b_energy_eV_ref"] = (df_pbe0.loc[:,"5b_energy_au"] - e_ref_b) * hartree_to_eV

df_pbe0.loc[:,"dE_eV_ref"] = df_pbe0.loc[:,"5b_energy_eV_ref"] - df_pbe0.loc[:,"5a_energy_eV_ref"]
df_pbe0

-4999.06027978
-4999.0642218

,sp method,opt method,5a_energy_au,5b_energy_au,dE_eV,5a_energy_eV_ref,5b_energy_eV_ref,dE_eV_ref
0,pbe0_def2tzvp,article_article,-4999.054146,-4999.057686,-0.096325,0.166898,0.177840,0.010943
1,pbe0_def2tzvp,matpes_pbe,-4999.050827,-4999.054039,-0.087417,0.257228,0.277080,0.019851
2,pbe0_def2tzvp,matpes_r2scan,-4999.055888,-4999.059767,-0.105559,0.119503,0.121212,0.001709
3,pbe0_def2tzvp,mpa_mpa,-4999.051394,-4999.054309,-0.079314,0.241798,0.269752,0.027954
4,pbe0_def2tzvp,omat24_omat24,-4999.051386,-4999.054621,-0.088020,0.242017,0.261265,0.019247
5,pbe0_def2tzvp,omol25_low,-4999.059019,-4999.063340,-0.117567,0.034299,0.023999,-0.010300
6,pbe0_def2tzvp,pbe0_def2svp,-4999.058998,-4999.063063,-0.110618,0.034873,0.031523,-0.003350
7,pbe0_def2tzvp,pbe0_def2tzvp,-4999.060280,-4999.064222,-0.107268,0.000000,0.000000,0.000000
8,pbe0_def2tzvp,pbe0_dgdzvp2,-4999.058794,-4999.062656,-0.105087,0.040425,0.042605,0.002180
9,pbe0_def2tzvp,pbe_def2svp,-4999.058532,-4999.062800,-0.116129,0.047552,0.038691,-0.008861
10,pbe0_def2tzvp,pbe_def2tzvp,-4999.055563,-4999.059600,-0.109857,0.128355,0.125766,-0.002589

In [12]:
e_ref_a = df_pbe.loc[df_pbe["opt method"] == "pbe_def2tzvp", "5a_energy_au"].iloc[0]
e_ref_b = df_pbe.loc[df_pbe["opt method"] == "pbe_def2tzvp", "5b_energy_au"].iloc[0]
print(e_ref_a)
print(e_ref_b)

df_pbe.loc[:,"5a_energy_eV_ref"] = (df_pbe.loc[:,"5a_energy_au"] - e_ref_a) * hartree_to_eV
df_pbe.loc[:,"5b_energy_eV_ref"] = (df_pbe.loc[:,"5b_energy_au"] - e_ref_b) * hartree_to_eV

df_pbe.loc[:,"dE_eV_ref"] = df_pbe.loc[:,"5b_energy_eV_ref"] - df_pbe.loc[:,"5a_energy_eV_ref"]
df_pbe

-4999.13101209
-4999.13330036

,sp method,opt method,5a_energy_au,5b_energy_au,dE_eV,5a_energy_eV_ref,5b_energy_eV_ref,dE_eV_ref
0,pbe_def2tzvp,article_article,-4999.130072,-4999.132496,-0.065971,0.025580,0.021876,-0.003704
1,pbe_def2tzvp,matpes_pbe,-4999.129773,-4999.131934,-0.058788,0.033706,0.037185,0.003479
2,pbe_def2tzvp,matpes_r2scan,-4999.129994,-4999.132919,-0.079578,0.027693,0.010382,-0.017311
3,pbe_def2tzvp,mpa_mpa,-4999.130069,-4999.131994,-0.052389,0.025675,0.035553,0.009878
4,pbe_def2tzvp,omat24_omat24,-4999.130033,-4999.132106,-0.056420,0.026645,0.032491,0.005847
5,pbe_def2tzvp,omol25_low,-4999.127026,-4999.130478,-0.093925,0.108472,0.076814,-0.031658
6,pbe_def2tzvp,pbe0_def2svp,-4999.121563,-4999.123890,-0.063321,0.257110,0.256056,-0.001054
7,pbe_def2tzvp,pbe0_def2tzvp,-4999.126568,-4999.128925,-0.064151,0.120942,0.119058,-0.001884
8,pbe_def2tzvp,pbe0_dgdzvp2,-4999.129686,-4999.132058,-0.064556,0.036095,0.033806,-0.002289
9,pbe_def2tzvp,pbe_def2svp,-4999.129887,-4999.132172,-0.062168,0.030603,0.030702,0.000099
10,pbe_def2tzvp,pbe_def2tzvp,-4999.131012,-4999.133300,-0.062267,0.000000,0.000000,0.000000

In [13]:
df_pbe0.drop(["sp method"], axis=1)

,opt method,5a_energy_au,5b_energy_au,dE_eV,5a_energy_eV_ref,5b_energy_eV_ref,dE_eV_ref
0,article_article,-4999.054146,-4999.057686,-0.096325,0.166898,0.177840,0.010943
1,matpes_pbe,-4999.050827,-4999.054039,-0.087417,0.257228,0.277080,0.019851
2,matpes_r2scan,-4999.055888,-4999.059767,-0.105559,0.119503,0.121212,0.001709
3,mpa_mpa,-4999.051394,-4999.054309,-0.079314,0.241798,0.269752,0.027954
4,omat24_omat24,-4999.051386,-4999.054621,-0.088020,0.242017,0.261265,0.019247
5,omol25_low,-4999.059019,-4999.063340,-0.117567,0.034299,0.023999,-0.010300
6,pbe0_def2svp,-4999.058998,-4999.063063,-0.110618,0.034873,0.031523,-0.003350
7,pbe0_def2tzvp,-4999.060280,-4999.064222,-0.107268,0.000000,0.000000,0.000000
8,pbe0_dgdzvp2,-4999.058794,-4999.062656,-0.105087,0.040425,0.042605,0.002180
9,pbe_def2svp,-4999.058532,-4999.062800,-0.116129,0.047552,0.038691,-0.008861
10,pbe_def2tzvp,-4999.055563,-4999.059600,-0.109857,0.128355,0.125766,-0.002589

In [40]:
df_pbe.drop(["sp method"], axis=1)

,opt method,5a_energy_au,5b_energy_au,dE_eV,5a_energy_eV_ref,5b_energy_eV_ref,dE_eV_ref
0,article_article,-4999.130072,-4999.132496,-0.065971,0.025580,0.021876,-0.003704
1,matpes_pbe,-4999.129773,-4999.131934,-0.058788,0.033706,0.037185,0.003479
2,matpes_r2scan,-4999.129994,-4999.132919,-0.079578,0.027693,0.010382,-0.017311
3,mpa_mpa,-4999.130069,-4999.131994,-0.052389,0.025675,0.035553,0.009878
4,omat24_omat24,-4999.130033,-4999.132106,-0.056420,0.026645,0.032491,0.005847
5,omol25_low,-4999.127026,-4999.130478,-0.093925,0.108472,0.076814,-0.031658
6,pbe0_def2svp,-4999.121563,-4999.123890,-0.063321,0.257110,0.256056,-0.001054
7,pbe0_def2tzvp,-4999.126568,-4999.128925,-0.064151,0.120942,0.119058,-0.001884
8,pbe0_dgdzvp2,-4999.129686,-4999.132058,-0.064556,0.036095,0.033806,-0.002289
9,pbe_def2svp,-4999.129887,-4999.132172,-0.062168,0.030603,0.030702,0.000099
10,pbe_def2tzvp,-4999.131012,-4999.133300,-0.062267,0.000000,0.000000,0.000000